name = "SabCore React Theme"
license = "MIT"
licenselink = "https://github.com/oke11o/sabcore-website/blob/main/LICENSE"
description = "SabCore React Theme - Hugo theme built from React components for AI-powered load testing platform."
homepage = "https://github.com/oke11o/sabcore-website"
demosite = "https://sabcore.io"
min_version = "0.141.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Zeon Studio"
homepage = "https://zeon.studio"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
